### ISSUE TITLE
zmod.exe opens and immediately closes

### ISSUE THREAD

**Issue by lattridge** [Fragonite/zmod#3]
I downloaded the mod and found my steam DW8 files and extracted the download into the DW8 file location. When I run zmod.exe the game opens up with a black square and then immediately closes.
It was working the first time I ran it, and then I ran the original game instead just to see the differences. Since then it hasn't worked.
I've tried reinstalling the game and the mod and it still doesn't work.
Any ideas what could be causing this and what I could do to fix it, please?

**Comment by Fragonite** [comment]
Did you get it working? Make sure your ini files are correct otherwise try restarting your PC and adding the mods one by one.

**Comment by Duoer18** [comment]
Maybe the resolution ratio configured in "zmod_dw8xlce_ultrawide.ini" should be consistent with your PC when you choose to play fullscreen, such as if your PC is 16:10, but you set "width=2560 and height=1440 (16: 9)" and play fullscreen, then it will immediately closes, thus, you should set "width=2560 and height=1600 (16: 10)".
